# Generated by Django 3.0.8 on 2020-07-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200721_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hs',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
